# Generated by Django 4.0.4 on 2022-09-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customgroup',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
