# Generated by Django 4.0.4 on 2022-09-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage_system', '0002_remove_customgroup_user_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='custom_group',
            field=models.ManyToManyField(blank=True, related_name='CustomGroup', to='user_manage_system.customgroup', verbose_name='CustomGroup'),
        ),
    ]
