# Generated by Django 4.0.4 on 2022-09-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage_system', '0003_alter_customgroup_name_alter_customuser_custom_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='custom_group',
            field=models.ManyToManyField(to='user_manage_system.customgroup'),
        ),
    ]
